### ISSUE TITLE
Parser.unescapeEntities equivalent

### ISSUE THREAD

**Issue by vanniktech** [MohamedRejeb/Ksoup#17]
It would be immensely helpful if the `ksoup-entites` module would provide an Parser.unescapeEntities equivalent Jsoup API:

https://jsoup.org/apidocs/org/jsoup/parser/Parser.html#unescapeEntities(java.lang.String,boolean)

With that one you can unescape all of the `&#1234;` entities.

My use case is that I have an RSS Reader and often times even though it's not required the content is HTML encoded and hence I need to unescape it. For instance here's on such feed: 

https://lexfridman.com/feed/podcast/

Note though that ideally any unicode would be supported, here are some more feeds which use a lot of escaped HTML entites:

https://vandal.elespanol.com/xml.cgi
https://open.firstory.me/rss/user/cklqae6gy388f0892i2qmv851
https://blog.codinghorror.com/rss/
https://www.ivoox.com/finanzas-personales-libertad-financiera_fg_f1703990_filtro_1.xml

**Comment by vanniktech** [comment]
In the meantime I did find [HTMLString](https://github.com/alexisakers/HTMLString) for iOS which does a superb parsing job. Really fast and I expect/actualed to each representation. 

Nonetheless, it would be really amazing if we had a fast implementation of `unescapeEntities ` here that would also work on the other targets like JS/Desktop.

**Comment by MohamedRejeb** [comment]
You can use `decodeHtml` which works the same as `unescapeEntities`:

`val decoded = KsoupEntities.decodeHtml("Hello &amp; World") // return: Hello & World`

Try it and let me know if this is what you are looking for

**Comment by vanniktech** [comment]
It does not work for instance Emojis are broken:

```kotlin
  @Test fun decodeEmoji() {
    assertEquals("", KsoupEntities.decodeHtml("&#127757;"))
  }
```

> java.lang.IllegalArgumentException
	at com.mohamedrejeb.ksoup.entities.utils.CharsUtils.toChars(CharsUtils.kt:29)
	at com.mohamedrejeb.ksoup.entities.text.translate.NumericEntityDecoder.translate(NumericEntityDecoder.kt:110)
	at com.mohamedrejeb.ksoup.entities.AggregateTranslator.translate(AggregateTranslator.kt:33)
	at com.mohamedrejeb.ksoup.entities.StringTranslator.translate(StringTranslator.kt:42)
	at com.mohamedrejeb.ksoup.entities.StringTranslator.translate(StringTranslator.kt:16)
	at com.mohamedrejeb.ksoup.entities.KsoupEntities.decodeHtml5(KsoupEntities.kt:318)
	at com.mohamedrejeb.ksoup.entities.KsoupEntities.decodeHtml(KsoupEntities.kt:348)

**Comment by MohamedRejeb** [comment]
Thanks for reporting this. I'll make sure to fix it ASAP.
