### ISSUE TITLE
com.mohamedrejeb.ksoup:ksoup-entites:0.3.1

### ISSUE THREAD

**Issue by vanniktech** [MohamedRejeb/Ksoup#40]
I had the same problem with 0.3.0 but didn't bother. Would it be possible that you publish all of the modules with the same version? That's what all of the popular libraries do (OkHttp, Retrofit, Sqldelight, etc)

**Comment by MohamedRejeb** [comment]
I'm publishing all modules with the same version.
Sorry for not mentioning this enough, but that artifact is renamed to `ksoup-entities` because it has a typo.
