### ISSUE TITLE
Can we access position/index of opening and closing tags?

### ISSUE THREAD

**Issue by rustamsmax** [MohamedRejeb/Ksoup#41]

**Comment by MohamedRejeb** [comment]
I thinking of adding support for having access to the HTML tree, but for now this is only possible manually by adding a variable, and you can increment and decrement it on tag open and close.
Also, you can even add a stack for the current tags.
You can check this code here to have a better idea [link](https://github.com/MohamedRejeb/Compose-Rich-Editor/blob/82db1a1892adc9a0b101465b2dc24263da30c0b6/richeditor-compose/src/commonMain/kotlin/com/mohamedrejeb/richeditor/parser/html/RichTextStateHtmlParser.kt#L21)

**Comment by rustamsmax** [comment]
Hi @MohamedRejeb I was planning to use it for multi platform compose html parsing. I've solved it using native functions with expect/actual function. Thank you!
