### ISSUE TITLE
Issues with & symbol

### ISSUE THREAD

**Issue by ladiesman2127** [MohamedRejeb/Ksoup#43]
Hi, how can I detect a character reference(&amp and etc). If i try to get it with onText Ksoup gives only & symbol.

**Comment by MohamedRejeb** [comment]
Hi,
Ksoup onText is going to return a text with decoded entities. If you want to encode them, you can use this: 
`val encoded = KsoupEntities.encodeHtml("Hello & World") // return: Hello &amp; World`
